language: node_js

env:
  global:
    - CXX=g++-4.8
    - NODE_ENV=production
    - secure: "BQ0BNb3D2gI3hYHXgNIgDNBfZu/koPlZS1mjFqxYizQM+Msu+Zg/QDyeIXFpR7oMU9bmTCWpL2gBFYTOwHAqdP8uDQSz42jCRVGPOmWE9rDt6MDNkyG2M6afJ5FH+bvdcnfWT387iaGfc3jqVZHTVhvy2ay3DTCy8eoovJ7KOZIE+G9YtUxKzNjQHzJaCTloKrvJGIrbebONwJ54LD4GWw4jb7NuUONMpJPwC3ukF6t0gvT83aUf5anrhiu8ghNVYJSObeIXhyiIckley08naETfoK3B/POVf9ex/DbippFhyj64UweNLZ+KAVXUhPBI/CieOG9EdeZQXm7b53ZsdsmDsItXP+nE7+ihfWM4gmv3WJnbLTy12W1D2AF0uoMI5U/jcwRwfoHxVo6OpMbpF10fUVn/yDM/90rpiaB50ufZHtB5cMQfOFGr6/PCiZI/omAi3frUC4Zx6ZbiaG019JqmFHYmrkbTL6d1DTuXL3fawW71tR5a/o4GhOePlu/pXh7nQp4hiRZVo/ZtY6Sa5iuS5UaHmu4uzkXRMurNGrySmSyAFkVxIWG/nHQVTqU1ahgxyYrbtve/aUHZH/aUKr/719N+NW+0ttRMZWAaPnRmbDNdDgyoqcvCr1GKBlaIDWFOMWc+Nd5rhHxaGXr3gthlQdqa4obpk2xdOkBijMw="
  matrix:
    - BUILDTYPE=development
    - BUILDTYPE=staging
    - BUILDTYPE=production

notifications:
  email: false

before_install:
  - npm install -g npm@3.8.9
  - npm --version

cache:
  apt: true
  directories:
  - node_modules
  - cache 

script:
  - ./script/travis-build.sh

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

before_deploy:
  - npm install -g s3-cli

deploy:
  - provider: script
    script: s3-cli sync --acl-public --delete-removed --recursive --region us-gov-west-1 build/development s3://dev.vets.gov/
    skip_cleanup: true
    on:
      repo: department-of-veterans-affairs/vets-website
      branch: master
      condition: "$BUILDTYPE == development"
  - provider: script
    script: s3-cli sync --acl-public --delete-removed --recursive --region us-gov-west-1 build/staging s3://staging.vets.gov/
    skip_cleanup: true
    on:
      repo: department-of-veterans-affairs/vets-website
      branch: master
      condition: "$BUILDTYPE == staging"
  - provider: script
    script: s3-cli sync --acl-public --delete-removed --recursive --region us-gov-west-1 build/production s3://www.vets.gov/
    skip_cleanup: true
    on:
      repo: department-of-veterans-affairs/vets-website
      branch: production
      condition: "$BUILDTYPE == production"
  - provider: s3
    access_key_id: AKIAIEIFFI3LJZO44VTQ
    secret_access_key:
      secure: PKZPLle45zyvca1I3w8gxkwznCWM/EUqfw7W8WOGmHBDqvnZ24Cc26pOSKDE8p250rnDX42cxrnOuuGJUNpVTWoIdtKrfi3YEZi8yBXwMecKHsaZO3jQrWtGFVHV747gDmjx7THsacgAn5mvgZkuHXOZXpWcJaQtOLjLhqx++tuKSuSOkFENlRjm5fZWGUkWCBR4HjJPdfFazl8sE7TDomuOEumCjtqeKNFumlrPs+H34OyMpiMidU24Nsbla0exV7YkJTJ2PrdtkYFB3p6zZP26CHv12odkCsauZ3Ee1MUcmolNb3VgK6RPGiBvcozP7u/SdbXb5JYwBT/x/ffkowCcIZ+PNSzh/QF/TdJ0c2vtkfhTCiBDiOnBosFf3DAFCtXRCLEIlJtlxDbavBLTIEMnwkNKAQIRZP5ro4zMGjAJP/AWE0YvYZCQO8YXlb/Pl8QsH8HZY2+EYR8Qrjg/NcnnDfkg9rGdyslY/e9oMoJYYgmJlwpuIMlAWylhqUHfCzGFtUzTV+8GARjM7kkMwtIUqsjBbEYNu+kzd7O8xuJEbPepXkS6jE5F+PzyoVIoWgOCsAHKsFmyRqDjwQVOgMchp8thUMillCcDnNsbTawZ78/MfKWtZd9bHAglSxjWavV6Yr6tNumiI/vyRoQNbc1nIpxwjnMd0lN5bpykTwY=
    bucket: staging.vets.gov
    skip_cleanup: true
    region: us-east-1
    local-dir: build/production
    acl: public_read
    on:
      repo: department-of-veterans-affairs/vets-website
      branch: master
      condition: "$BUILDTYPE == production"
  - provider: s3
    access_key_id: AKIAJPGY3X77ZMIBM4OA
    secret_access_key:
      secure: m5rN6YkmhW8kCsd6lc7szFHmPy4iFuc8fXMLRUIGTQQCLok2xdbsx6J4CPEYbjoECTmvQ0HyBfrYDAgR9SypxBprjAs5vBUaccXxB9G9cTWinJrSRbAY2COXVXxWNfjqHZF0Jfk3UH/bzTx72BJL58vkb844RS/pEWBA/HiTmSpKTFaXwQzussMVuJdF4CROvymX0sHBurHap5Jdzytr2lV22cJ10/60rbc8S7XVACloIxsD/n/HJr79wf9J44gHbzjKEpvWpz3jsF/jTHkXkGuq/Li9qaD9mM9dCVYv7AlzXm8Wm4r8IP/qriIuOYsPouyiZHuky6y3oGDD6BaH6JAAUBwVX1e8FfxEjvDGQP4T6K0y3memwIE1NiI3JJbaqSAlNkgfHXwqE5WeP0XThK30X0B41Uu661YgGh9lTu9a2R9+XKPGjxoAi14RFNtMvS7Pwzv2jrUM7UD/7dfIQc0q3s1j/kaHkAlXi9CCvhAB9WRUXSuMJv+Zdcaua5XK0SSO8pBYT/NaY/3rI6G03I3vWG06KRZwsF0ilo2RKBtx+wH1K7tt33LBJdAx/AScoYMyY0hWCKZvtnKlvOc9Ucexy3JDC9aNOG3cvX4u5jPJLI5dpzZJE2dye5BucKkane999hmI37pgvgVE1/qdaN+NjyrGM/CX5kBs9JUfCe8=
    bucket: www.vets.gov
    skip_cleanup: true
    region: us-east-1
    local-dir: build/production
    acl: public_read
    on:
      repo: department-of-veterans-affairs/vets-website
      branch: production
      condition: "$BUILDTYPE == production"
