name: Vets.gov

domain: staging.vets.gov

#files to exclude, array
exclude:
  - README.md
  - Rakefile
  - "/vendor/bundle"
  - Gemfile
  - Gemfile.lock
  - CNAME

#posts per page
paginate: 2
paginate_path: "/experience/:num/"

excerpt_separator: <!--more-->

#number of items in RSS feed
rss_limit: 20

#whether production or dev, minifies JS, bool
production: true

#build config

timezone: America/New_York
encoding: UTF-8
safe: true

markdown: kramdown
timezone: America/New_York
encoding: UTF-8

kramdown:
  parse_block_html: true
  input: GFM

sass:
  sass_dir: _sass
  style: :compressed
  images_dir: 'img/content'
  javascripts_dir: 'assets/js'

collections:
  # further define collections here
  disability-benefits:
    output: true
    permalink: /disability-benefits/:path/
  education:
    output: true
    permalink: /education/:path/
  loans:
    output: true
    permalink: /loans/:path/
  pension:
    output: true
    permalink: /pension/:path/
  insurance:
    output: true
    permalink: /insurance/:path/
  memorial:
    output: true
    permalink: /memorial/:path/
  compensation:
    output: true
    permalink: /compensation/:path/
  family:
    output: true
    permalink: /family/:path/
  playbook:
    output: true
    permalink: /playbook/:path/
  facility-locator:
    output: true
    permalink: /facility-locator/