  
  
inputs:
  key:
    description: keys for actions/cache@v2
    required: false
    default: ''

runs:
  using: composite  
  steps:
    - name: Install dependencies
      uses: ./.github/workflows/install
      with:
        key: ${{ hashFiles('yarn.lock') }}
        yarn_cache_folder: .cache/yarn
        path: |
          .cache/yarn
          node_modules

    - name: List changed files
      id: changed-files
      shell: bash
      run: |
        if [[ ${{ github.ref }} == 'refs/heads/master' ]]; then
          echo ::set-output name=all_changed_files::$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }})
        else
          echo ::set-output name=all_changed_files::$(git diff --name-only origin/master...)
        fi

    - name: Get app entries for changed files
      id: get-changed-apps
      shell: bash
      run: echo ::set-output name=app_entries::$(node script/github-actions/get-changed-apps.js)
      env:
        CHANGED_FILE_PATHS: ${{ steps.changed-files.outputs.all_changed_files }}

    - name: Audit dependencies
      if: steps.get-changed-apps.outputs.app_entries == ''
      shell: bash
      run: yarn security-check
