name: Linting
on: [push]

jobs:
  plain-language:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Run Vale
        uses: errata-ai/vale-action@v1.0.4
        with:
          styles: |
            https://github.com/errata-ai/write-good/releases/latest/download/write-good.zip
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
